apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:iremmats/gitops-demos.git
---
## Makes this application manage itself.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: app-of-apps
  source:
    path: clusters/
    repoURL: git@github.com:iremmats/gitops-demos.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-yellow-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: app-of-apps
  source:
    path: clusters/yellow/
    repoURL: git@github.com:iremmats/gitops-demos.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-purple-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: app-of-apps
  source:
    path: clusters/purple/
    repoURL: git@github.com:iremmats/gitops-demos.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-tools-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: app-of-apps
  source:
    path: clusters/tools/
    repoURL: git@github.com:iremmats/gitops-demos.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true