apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: 03-app02
    name: 03-app02
  name: 03-app02
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: 03-app02
        name: 03-app02
    spec:
      containers:
      - env:
        - name: ANOTHER_ENV_VAR
          value: "21234567"
        image: tutum/hello-world
        name: 03-app02
        ports:
        - containerPort: 80
          name: http
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx-external
    kubernetes.io/tls-acme: "true"
  labels:
    app: 03-app02
    name: 03-app02
  name: 03-app02
spec:
  rules:
  - host: 03-app02.matsiremark.com
    http:
      paths:
      - backend:
          serviceName: svc-03-app02
          servicePort: 80
        path: /
  tls:
  - hosts:
    - 03-app02.matsiremark.com
    secretName: 03-app02-tls
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  labels:
    name: 03-app02
  name: app2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: 03-app02
    name: svc-03-app02
  name: svc-03-app02
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app: 03-app02
    name: 03-app02
  type: ClusterIP