apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    namespace: app1
    server: https://yellow-a2a4e2e7.hcp.westeurope.azmk8s.io:443
  project: 02-apps
  source:
    path: 02/app1
    repoURL: git@github.com:iremmats/cloud-native-7.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  destination:
    namespace: app2
    server: https://yellow-a2a4e2e7.hcp.westeurope.azmk8s.io:443
  project: 02-apps
  source:
    path: 02/app2
    repoURL: git@github.com:iremmats/cloud-native-7.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true