apiVersion: v1
data:
  repositories: |
    - sshPrivateKeySecret:
        key: sshPrivateKey
        name: repo-gitops-demos-316249281
      type: git
      url: git@github.com:iremmats/gitops-demos.git
    - name: Jetstack
      type: helm
      url: https://charts.jetstack.io
    - name: Stable
      type: helm
      url: https://kubernetes-charts.storage.googleapis.com
    - name: Bitnami
      type: helm
      url: https://charts.bitnami.com/bitnami
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd